#!/bin/bash

function __aws_ps1 () {
    if ! [ -z "${aws_profile}" ]; then
        printf " (${aws_profile})";
    fi
}

function aws_set_profile () {
	. ${HOME}/gls/bin2/sourced/export-aws-env-vars.sh ${@}	
}

function aws_unset_profile () {
	aws_set_profile "unset"
}

