#!/bin/bash

function _aws_set_profile_completion {
	local currword="${COMP_WORDS[COMP_CWORD]}"
	local options="$(pcregrep -o1 "^\[profile (.*)\]$"  ~/.aws/config)"
	COMPREPLY=($(compgen -W "${options}" "${currword}" ))
}
complete -F _aws_set_profile_completion aws_set_profile 

